import json,hashlib,re,csv
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parent
NOW=datetime.now(timezone.utc).isoformat()
A=json.loads((ROOT/'reward-source-audit.json').read_text(encoding='utf-8'))
# A successful HTTP response is not necessarily usable evidence.
for s in A:
 if s.get('status')=='fetched' and s.get('characters',0)<300:s['status']='insufficient_text'
(ROOT/'reward-source-audit.json').write_text(json.dumps(A,ensure_ascii=False,indent=2),encoding='utf-8')
S={x['url']:x for x in A}
def source(url,kind='issuer',note=''):
 s=S.get(url,{})
 return {'url':url,'kind':kind,'access':s.get('status','previous_or_web_read'),'content_file':s.get('content_file'),'sha256':s.get('content_sha256'),'note':note}
registry=[]
def add(name,year,eco,rules,result,level,urls,lesson,unknown,amount=None,recipients=None,event_date=None,operation='historical_product_evidence',tags=()):
 registry.append({'project':name,'reward_year':year,'event_date':event_date,'ecosystems':eco,'rules_summary':rules,'payout_summary':result,'payout_evidence_level':level,'reported_amount':amount,'reported_recipients':recipients,'current_operation_check':operation,'sources':[source(u) if isinstance(u,str) else u for u in urls],'agent_lesson':lesson,'unknowns':unknown,'tags':list(tags),'fine_tuning_eligible':False,'review_status':'source_checked_partial_dossier','reviewed_at':NOW})
# Retain earlier facts; do not translate allocation fields into paid totals.
old=json.loads((ROOT.parent/'historical-cases.json').read_text(encoding='utf-8'))['cases']
levels={'Aptos':'issuer_reported_distribution','Uniswap':'published_claim_analysis','Arbitrum':'published_claim_analysis','Pyth':'issuer_reported_claims','EigenLayer':'published_claim_analysis','ENS':'issuer_reported_claims','Optimism':'issuer_reported_distribution','1inch':'issuer_reported_distribution','dYdX':'earned_not_claimed','Sui':'sale_not_reward'}
for c in old:
 if c['project'] not in {'Uniswap','Arbitrum','Celestia','Starknet','ZKsync','Sui','Aptos','Jito','Pyth','Wormhole','EigenLayer','ENS','Optimism','dYdX','1inch'}:continue
 out=c.get('outcome') or {};rep=c.get('reported_outcome') or {}
 result=out.get('statement') or ('Опубліковано аналіз claims; незалежний запит ще не відтворено.' if rep else 'Підсумок фактичних виплат у зібраному досьє ще не підтверджений.')
 add(c['project'],c['year'],['Cosmos'] if c['project']=='Celestia' else [],c['finding'],result,levels.get(c['project'],'allocation_or_rules_only'),[source(x['url'],'published_analysis' if 'dragonfly' in x['url'] else 'issuer') for x in c['sources']],c['product_lesson'],['Точні виплати та кількість адрес потребують окремого аудиту.','Фактичні витрати та чистий результат учасників невідомі.','Поточна працездатність не перевірена живою транзакцією.'],tags=[c['category']])
 registry[-1]['legacy_case']=c
 registry[-1]['reported_claim_analysis']=rep or None
 registry[-1]['operation_evidence']=c.get('mainnet')
# New project dossiers. Summaries are paraphrases; quantities remain scoped.
add('Monad',2025,['Monad'],'П’ять напрямів: внесок у спільноту; активні onchain-користувачі; криптоспільноти; розробники Monad; публічні блага й освіта. Враховано довготривалий внесок, ручний перегляд і рекомендації спільноти. Вікно claim: 14.10–03.11.2025.','Фонд повідомив про 3,33 млрд MON claims. CSV містить 76 021 унікальну адресу і точно 3 330 583 396 MON; медіана 12 000 MON. Звіт описує escrow 09.11 і видачу при mainnet 24.11; Dune опублікував підсумок після запуску.','issuer_reported_claims',[ 'https://monad.xyz/blog/the-mon-airdrop-results','https://docs.monad.xyz/',source('https://dune.com/blog/dune-digest-037','published_analysis'),source('https://raw.githubusercontent.com/monad-crypto/airdrop-addresses/main/monad_airdrop_results.csv','issuer_dataset')],'Тестнет-транзакції не дорівнюють гарантованій алокації. Вчити класифікацію внесків, об’єднання субкатегорій і різницю між escrow та доступними коштами.',['Не відтворено всі перекази escrow → одержувач.','Не пораховано витрати або прибуток кожного учасника.'],3330583396,76021,'2025-11-24',tags=['community_contribution','developer','public_goods','multi_cohort','claim_window'])
add('Arkham',2023,['Ethereum'],'Початкова роздача 2023: ранні користувачі конвертували points через Invite Dashboard; початкове вікно закривалося 16.07 о 19:00 UTC. Біржова програма 2024–2025 — окремий сезон з іншими умовами.','Офіційний канал підтвердив відкриття видачі ARKM. Окремо 18.04.2025 Arkham повідомив про понад $20 млн винагород у біржовому Season 1. Це не сума початкової роздачі 2023.','issuer_reported_distribution',['https://t.me/s/arkhamintelligence?before=89','https://info.arkm.com/announcements/arkham-exchange-updates-2'],'Не переносити умови або результати біржового сезону на початковий реферальний airdrop. Один проєкт може мати кілька різних механік.',['Точна формула початкових points і сума claims 2023 ще не відтворені.','Методика доларової оцінки Season 1 не наведена.'],tags=['referral','points','multi_season','real_capital'])
registry[-1]['additional_reward_years']=[2025]
add('Plasma',2025,['Plasma'],'Офіційно анонсовано бонус 25 млн XPL для малих депозитаріїв, які пройшли Sonar-перевірку та взяли участь у продажу. Окремо продано 10% supply; 2,5 млн XPL зарезервовано для Stablecoin Collective.','Анонс визначає дату 25.09.2025. Yield Network повідомляє про виконані розподіли після запуску, але повний набір підтвердних транзакцій у статті не надано. Тому його цифри не прийнято за незалежно перевірені.','published_distribution_analysis',['https://www.plasma.org/company/blog/plasma-mainnet-beta-and-xpl',source('https://www.yieldnetwork.io/blog/plasma-predeposit','published_analysis','Потребує відтворення; не використовувати твердження про нульові витрати.')],'Зберігати продаж, бонус і резерв спільноти окремо. Депозит, KYC, блокування та нові кошти для купівлі — різні вимоги.',['Первинне підтвердження всіх бонусних переказів.','Повна формула добору менших депозитаріїв.','Незалежна перевірка чисел вторинного аналізу.'],event_date='2025-09-25',tags=['deposit','kyc','sale_plus_bonus','real_capital'])
add('Somnia',2025,['Somnia'],'Квести й тестнет, контент і внески спільноти; окремі категорії SomniYaps, Quills і Discord. Для основної групи: 20% одразу, 80% через вісім щотижневих частин по 10%; приблизно 90 днів на виконання. В Odyssey обов’язкові місії потребували gas, платні bonus-місії були добровільні.','Підтверджено mainnet 02.09.2025 та офіційну післязапускову інструкцію розблокування. Фінальний обсяг отриманих SOMI і кількість одержувачів ще не перевірені; початкові 5% supply — алокація.','live_claim_program',['https://blog.somnia.network/p/say-hi-to-somi','https://blog.somnia.network/p/the-somnia-odyssey-a-60-day-adventure','https://www.improbable.io/news/improbable-developed-somnia-launches-mainnet-after-record-breaking-testnet-performance'],'Агент має вести післязапусковий календар. Не трактувати 60 днів як автоматичне отримання 100% без виконання умов.',['Підсумок claims і повернених невитребуваних токенів.','Реальні витрати учасників.'],event_date='2025-09-02',tags=['testnet','community_contribution','conditional_unlock','gas','optional_tasks'])
add('Osmosis',2021,['Cosmos'],'Snapshot ATOM 18.02.2021; алокація пропорційна квадратному кореню балансу, зі спеціальним множником 2,5 для стейкінгу. 20% у genesis; по 20% за swap, LP, staking і governance. Початкове повне вікно — два місяці, далі чотири місяці спадання.','Документація фіксує початковий випуск 100 млн OSMO, половина — fairdrop. Повний список отриманих після виконання завдань сум у цій перевірці ще не відтворено.','genesis_distribution_documented',['https://osmosis.gitbook.io/o/osmo/genesis-supply','https://osmosis.gitbook.io/o/osmo/airdrop-claim','https://osmosis.gitbook.io/o/osmo/token-distribution'],'Баланс, stake-множник, завдання після запуску та зменшення claimable — окремі змінні.',['Точний остаточний claim і сума clawback.','Витрати на LP та транзакції.'],tags=['staking','snapshot','conditional_unlock','decay','real_capital'])
add('Juno',2021,['Cosmos'],'Stakedrop ATOM-стейкерам; офіційний вступ описує 47% genesis supply і співвідношення 1:1. Детальні caps та exclusions ще потребують окремої перевірки.','Офіційна документація підтверджує запуск 01.10.2021 і входження всіх початкових JUNO в обіг через genesis. Незалежний перерахунок відповідних балансів не виконано.','genesis_distribution_documented',['https://docs.junonetwork.io/'],'Не трактувати короткий опис 1:1 як повну формулу без caps, винятків і правил агрегування адрес.',['Повні snapshot, caps та exclusions.','Незалежна перевірка початкових одержувачів.'],event_date='2021-10-01',tags=['staking','genesis'])
add('Stride',2022,['Cosmos'],'Для host-chain роздач — стейкінг на snapshot; нижня межа $100 і cap $50 000 за ціною snapshot. Зазвичай виключені біржові валідатори. Початкове вікно claim три місяці; невитребувана частина перерозподілялася початковим одержувачам.','Офіційний оновлений звіт станом на 07.09.2023 повідомляє про мільйони STRD, отримані десятками тисяч адрес. Точних значень у цьому тексті немає.','issuer_reported_claims',['https://stride.zone/blog/stride-airdrop-details','https://stride.zone/blog/airdrop-to-sttia-holders'],'Невитребувані токени можуть перерозподілятися, а не повертатися казначейству. Правила stTIA 2024 з відкладеним claim не змішувати з genesis-програмою.',['Точні суми за кожною мережею й snapshot.','Чисті результати після витрат.'],tags=['staking','threshold','cap','validator_exclusion','redistribution'])
add('Neutron',2023,['Cosmos'],'Початкові правила: понад 1 ATOM на блоці 12 900 000 (19.11.2022), окремий пул учасникам голосування за proposal 72; виключення CEX/custodians.','Поточні офіційні tokenomics описують 7% supply як роздані ATOM-стейкерам та іншим учасникам. 70 млн — опублікована категорія; точний user-claim не прирівняний до неї, бо частина залишилась невитребуваною.','issuer_reported_distribution',['https://docs.neutron.org/concepts/tokenomics','https://forum.cosmos.network/t/proposal-792-accepted-launch-neutron-on-replicated-security/10230/90'],'Умови стейкінгу й голосування мають власні пули. Загальна airdrop-категорія tokenomics не дорівнює user-claim.',['Відтворення claims та переказу залишку спільноті.','Повна формула кожного пулу.'],tags=['staking','governance','snapshot','validator_exclusion'])
add('Stargaze',2022,['Cosmos'],'Snapshot 11.10.2021; ATOM-stake від 5, OSMO-stake від 50, LP та окремі validator-категорії. Опубліковано 2 453 STARS за кожну відповідну роль; ролі могли підсумовуватися. CEX-делегації виключені. Для claim потрібні дії у продукті.','Пропозиція запуску airdrop пройшла у січні 2022; це доказ активації програми, але не перерахунок усіх виплат.','live_claim_program',['https://paragraph.com/@stargazezone/stars-token-distribution-and-airdrop',source('https://stargaze.valopers.com/proposals/4','chain_explorer')],'Рольові винагороди можуть сумуватися. Перевіряти версії строків decay: governance могла змінити первинний план.',['Остаточні правила після governance-змін.','Фактична сума й адреси claims.'],tags=['staking','liquidity','multi_cohort','conditional_unlock'])
add('Avail',2024,['Polygon','Ethereum rollups','Cosmos'],'Unification Drop: developers, тестнет Clash of Nodes, rollup users, Polygon PoS stakers, внески спільноти. Snapshot для стейкерів/rollup users — 31.03.2024. Phase 1 до 04.05; Phase 2 продовжена до 15.05.2024 16:00 UTC.','Звіт за 2024 підтверджує mainnet, запуск токена й Unification Drop; Polygon позначає кампанію завершеною. 600 млн AVAIL і 354 605 eligible-адрес — початковий план, не перевірений фінальний payout.','completed_program_reported',['https://blog.availproject.org/avails-unification-drop/','https://blog.availproject.org/avail-2024-wrapped/','https://staking.polygon.technology/community-drops'],'Перевірка права до mainnet і отримання токенів під час mainnet — різні події. Зберігати продовження дедлайнів.',['Точний фактичний розподіл і exclusions за кожною фазою.'],tags=['developer','testnet','staking','multi_cohort','sybil_filter','claim_window'])
add('Saga',2024,['Cosmos','Polygon','Celestia','Avalanche'],'ATOM: збільшення stake 20.04–20.10.2023 ТА понад 25 ATOM 20.10. TIA: понад 23 станом на 01.12.2023. Polygon: понад 300 MATIC на 20.10.2023 АБО міст zkEVM понад 0,4 ETH. Окремі loyalty-бонуси та developer/game-когорти.','Polygon Staking позначає Genesis-кампанію завершеною. Фінальний onchain-підрахунок поки відсутній.','completed_program_reported',['https://medium.com/sagaxyz/saga-community-genesis-airdrop-e0f94c1f2220','https://staking.polygon.technology/community-drops'],'Критична різниця AND/OR і строгих > порогів. Один проєкт, кілька екосистем; не рахувати чотири проєкти.',['Фінальні claims.','Поточний статус мережі після організаційних змін 2026 потребує окремої перевірки.'],tags=['staking','bridge','multi_cohort','loyalty','and_or'])
add('Dymension',2024,['Cosmos','Ethereum','Solana'],'Genesis Rolldrop: опублікована алокація 70 млн DYM, реєстрація до 21.01.2024 12:00 UTC, невитребувану частину мали перерозподілити. Публічний репозиторій містить механізм genesis allocations.','Збережено офіційний репозиторій; фактичне застосування всіх алокацій у фінальному genesis ще не перераховано.','allocation_or_rules_only',['https://medium.com/@dymension/genesis-rolldrop-the-first-rolldrop-season-219c8b5ea16e','https://github.com/dymensionxyz/rolldrop-genesis'],'Публічний генератор genesis і фактичний genesis мережі — різні докази.',['Перевірка повної eligibility-формули.','Підсумковий genesis та отримані баланси.'],tags=['genesis','redistribution','claim_window'])
add('Stellar',2019,['Stellar'],'Keybase Space Drop: автентифіковані акаунти; планувалося до 2 млрд XLM протягом 20 місяців.','Збережено анонс SDF. Повний план не прирівняно до виконаних виплат; підсумок і дострокове завершення ще потребують первинного підтвердження.','allocation_or_rules_only',['https://stellar.org/blog/foundation-news/keybase-stellar-lumens-spacedrop'],'Навіть план з місячними виплатами може завершитися раніше; навчальний label має спиратися на виконаний результат.',['Фінальна сума виплат і дата завершення програми.'],tags=['identity','recurring_distribution'])
# Do not conflate the chains requested by the user with their ecosystem reward issuers.
ecosystems=[{'name':'Cosmos','count_as_reward_project':False,'meaning':'Екосистема та ATOM як умова участі; роздачі окремих Osmosis/Juno/Stride/Neutron/Stargaze/Celestia рахуються за емітентом.'},{'name':'Polygon','count_as_reward_project':False,'meaning':'Екосистема; в цій вибірці історичні винагороди Avail і Saga. MATIC→POL не класифікується як винагорода. Planet Mojo: черга перевірки, лише статус Finished на офіційній сторінці.','source_url':'https://staking.polygon.technology/community-drops'}]
# Attach exact SQL models as audit leads, not executed payouts.
models=[]
idx=json.loads((ROOT/'dune-model-index.json').read_text())
for p in idx['paths']:
 if '/projects/' not in p or not p.endswith('.sql'):continue
 f=ROOT/'dune-models'/p.split('/')[-1]
 if not f.exists():continue
 t=f.read_text();m=re.search(r"'([^']+)'\s+AS\s+project",t,re.I);tok=re.search(r"'([^']+)'\s+AS\s+token_symbol",t,re.I)
 models.append({'project_key':m.group(1) if m else p.split('/')[-1].split('_ethereum_')[0],'model_url':'https://github.com/duneanalytics/spellbook/blob/main/'+p,'local_model':str(f.relative_to(ROOT)),'token':tok.group(1) if tok else None,'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'query_executed':False,'payout_verified':False,'review_status':'onchain_model_available_not_results'})
(ROOT/'claim-model-candidates.json').write_text(json.dumps(models,ensure_ascii=False,indent=2),encoding='utf-8')
# Curated extensions remain separate and survive every rebuild.
exp_audit_path=ROOT/'expansion-source-audit.json'
exp_audit={x['url']:x for x in json.loads(exp_audit_path.read_text(encoding='utf-8'))} if exp_audit_path.exists() else {}
seen={x['project'].casefold() for x in registry}
for path in sorted(ROOT.glob('expansion-curated-*.json')):
 for row in json.loads(path.read_text(encoding='utf-8-sig')):
  key=row['project'].casefold()
  if key in seen:raise ValueError('Duplicate issuer: '+row['project'])
  seen.add(key)
  for src in row['sources']:
   ev=exp_audit.get(src['url'],{})
   src['direct_fetch_status']=ev.get('status','not_attempted')
   if ev.get('status')=='fetched':
    src.update(access='direct_text_fetched',content_file=ev['content_file'],sha256=ev['content_sha256'],hash_scope='extracted_text_utf8')
  registry.append(row)
for row in registry:
 row.setdefault('scope_status','sale_comparison_excluded_target' if row['payout_evidence_level']=='sale_not_reward' else 'historical_candidate_current_operation_not_verified')
scope={'window':{'from':'2018-09-29','to':'2026-09-29','date_applies_to':'reward_distribution_event'},'target_unique_projects':1000,'unit':'unique reward-issuing project; multiple seasons and ecosystems do not increase count','requires':'Historical launched product and documented executed rewards; current operating status recorded separately.','excludes':['current speculative testnets','sale-only allocations','token migrations','unexecuted announcements from confirmed payout count'],'research_may_include_paid_historical_activity':True,'does_not_authorize_live_financial_actions':True,'status':'incomplete','ecosystems':ecosystems,'projects':registry,'schema_version':2}
(ROOT/'historical-rewards.json').write_text(json.dumps(scope,ensure_ascii=False,indent=2),encoding='utf-8')
with (ROOT/'historical-rewards.csv').open('w',encoding='utf-8-sig',newline='') as f:
 keys=['project','reward_year','event_date','ecosystems','rules_summary','payout_summary','payout_evidence_level','scope_status','current_operation_check','agent_lesson','unknowns','source_urls']
 w=csv.DictWriter(f,fieldnames=keys);w.writeheader()
 for x in registry:w.writerow({**{k:x.get(k) for k in keys[:-1]},'ecosystems':'; '.join(x['ecosystems']),'unknowns':'; '.join(x['unknowns']),'source_urls':' | '.join(s['url'] for s in x['sources'])})
print(json.dumps({'dossiers':len(registry),'claim_models':len(models),'model_projects':len({m['project_key'] for m in models}),'target_completed':False}))
